package tui

import (
	"time"

	"github.com/panz3r/depsclean/internal/model"
)

// FixtureResults returns a set of realistic fake scan results for development/demo.
func FixtureResults() []model.Result {
	now := time.Now()
	return []model.Result{
		{
			ID:             "/Users/dev/projects/my-react-app/node_modules",
			Path:           "/Users/dev/projects/my-react-app/node_modules",
			ProjectPath:    "/Users/dev/projects/my-react-app",
			Basename:       "node_modules",
			SizeBytes:      512 * 1024 * 1024,
			LastModified:   now.Add(-72 * time.Hour),
			Status:         model.StatusReady,
			PackageManager: model.PackageManagerNPM,
			PackageName:    "my-react-app",
			PackageVersion: "1.0.0",
		},
		{
			ID:             "/Users/dev/projects/next-dashboard/node_modules",
			Path:           "/Users/dev/projects/next-dashboard/node_modules",
			ProjectPath:    "/Users/dev/projects/next-dashboard",
			Basename:       "node_modules",
			SizeBytes:      820 * 1024 * 1024,
			LastModified:   now.Add(-24 * time.Hour),
			Status:         model.StatusReady,
			PackageManager: model.PackageManagerNPM,
			PackageName:    "next-dashboard",
			PackageVersion: "0.2.1",
		},
		{
			ID:             "/Users/dev/projects/vue-shop/node_modules",
			Path:           "/Users/dev/projects/vue-shop/node_modules",
			ProjectPath:    "/Users/dev/projects/vue-shop",
			Basename:       "node_modules",
			SizeBytes:      340 * 1024 * 1024,
			LastModified:   now.Add(-7 * 24 * time.Hour),
			Status:         model.StatusReady,
			PackageManager: model.PackageManagerYarn,
			PackageName:    "vue-shop",
			PackageVersion: "3.1.0",
		},
		{
			ID:             "/Users/dev/projects/api-gateway/node_modules",
			Path:           "/Users/dev/projects/api-gateway/node_modules",
			ProjectPath:    "/Users/dev/projects/api-gateway",
			Basename:       "node_modules",
			SizeBytes:      215 * 1024 * 1024,
			LastModified:   now.Add(-30 * 24 * time.Hour),
			Status:         model.StatusReady,
			PackageManager: model.PackageManagerNPM,
			PackageName:    "api-gateway",
			PackageVersion: "2.0.0",
		},
		{
			ID:             "/Users/dev/projects/design-system/node_modules",
			Path:           "/Users/dev/projects/design-system/node_modules",
			ProjectPath:    "/Users/dev/projects/design-system",
			Basename:       "node_modules",
			SizeBytes:      650 * 1024 * 1024,
			LastModified:   now.Add(-14 * 24 * time.Hour),
			Status:         model.StatusReady,
			PackageManager: model.PackageManagerPNPM,
			PackageName:    "design-system",
			PackageVersion: "1.5.2",
		},
		{
			ID:             "/Users/dev/projects/mobile-app/node_modules",
			Path:           "/Users/dev/projects/mobile-app/node_modules",
			ProjectPath:    "/Users/dev/projects/mobile-app",
			Basename:       "node_modules",
			SizeBytes:      1200 * 1024 * 1024,
			LastModified:   now.Add(-2 * time.Hour),
			Status:         model.StatusReady,
			PackageManager: model.PackageManagerBun,
			PackageName:    "mobile-app",
			PackageVersion: "0.1.0",
		},
		{
			ID:             "/Users/dev/projects/legacy-backend/node_modules",
			Path:           "/Users/dev/projects/legacy-backend/node_modules",
			ProjectPath:    "/Users/dev/projects/legacy-backend",
			Basename:       "node_modules",
			SizeBytes:      90 * 1024 * 1024,
			LastModified:   now.Add(-365 * 24 * time.Hour),
			Status:         model.StatusDeleted,
			PackageManager: model.PackageManagerNPM,
			PackageName:    "legacy-backend",
			PackageVersion: "0.0.1",
		},
		{
			ID:             "/Users/dev/projects/broken-tool/node_modules",
			Path:           "/Users/dev/projects/broken-tool/node_modules",
			ProjectPath:    "/Users/dev/projects/broken-tool",
			Basename:       "node_modules",
			SizeBytes:      0,
			LastModified:   now.Add(-48 * time.Hour),
			Status:         model.StatusError,
			PackageManager: model.PackageManagerNPM,
			PackageName:    "broken-tool",
			ErrorMsg:       "permission denied",
		},
		{
			ID:             "/Users/dev/projects/monorepo/packages/ui/node_modules",
			Path:           "/Users/dev/projects/monorepo/packages/ui/node_modules",
			ProjectPath:    "/Users/dev/projects/monorepo/packages/ui",
			Basename:       "node_modules",
			SizeBytes:      120 * 1024 * 1024,
			LastModified:   now.Add(-3 * 24 * time.Hour),
			Status:         model.StatusReady,
			PackageManager: model.PackageManagerYarn,
			PackageName:    "@monorepo/ui",
			PackageVersion: "1.0.0",
		},
		{
			ID:             "/Users/dev/projects/monorepo/packages/core/node_modules",
			Path:           "/Users/dev/projects/monorepo/packages/core/node_modules",
			ProjectPath:    "/Users/dev/projects/monorepo/packages/core",
			Basename:       "node_modules",
			SizeBytes:      85 * 1024 * 1024,
			LastModified:   now.Add(-3 * 24 * time.Hour),
			Status:         model.StatusReady,
			PackageManager: model.PackageManagerYarn,
			PackageName:    "@monorepo/core",
			PackageVersion: "1.0.0",
		},
		{
			ID:             "/Users/dev/projects/electron-app/node_modules",
			Path:           "/Users/dev/projects/electron-app/node_modules",
			ProjectPath:    "/Users/dev/projects/electron-app",
			Basename:       "node_modules",
			SizeBytes:      1800 * 1024 * 1024,
			LastModified:   now.Add(-60 * 24 * time.Hour),
			Status:         model.StatusReady,
			PackageManager: model.PackageManagerNPM,
			PackageName:    "electron-app",
			PackageVersion: "2.3.1",
		},
		{
			ID:             "/Users/dev/sandbox/test-project/node_modules",
			Path:           "/Users/dev/sandbox/test-project/node_modules",
			ProjectPath:    "/Users/dev/sandbox/test-project",
			Basename:       "node_modules",
			SizeBytes:      45 * 1024 * 1024,
			LastModified:   now.Add(-5 * time.Minute),
			Status:         model.StatusPending,
			PackageManager: model.PackageManagerNPM,
			PackageName:    "test-project",
		},
		{
			ID:             "/Users/dev/projects/cli-tool/node_modules",
			Path:           "/Users/dev/projects/cli-tool/node_modules",
			ProjectPath:    "/Users/dev/projects/cli-tool",
			Basename:       "node_modules",
			SizeBytes:      55 * 1024 * 1024,
			LastModified:   now.Add(-10 * 24 * time.Hour),
			Status:         model.StatusReady,
			PackageManager: model.PackageManagerPNPM,
			PackageName:    "cli-tool",
			PackageVersion: "1.2.3",
		},
		{
			ID:             "/Users/dev/projects/docs-site/node_modules",
			Path:           "/Users/dev/projects/docs-site/node_modules",
			ProjectPath:    "/Users/dev/projects/docs-site",
			Basename:       "node_modules",
			SizeBytes:      280 * 1024 * 1024,
			LastModified:   now.Add(-20 * 24 * time.Hour),
			Status:         model.StatusReady,
			PackageManager: model.PackageManagerBun,
			PackageName:    "docs-site",
			PackageVersion: "0.5.0",
		},
		{
			ID:             "/Users/dev/projects/graphql-server/node_modules",
			Path:           "/Users/dev/projects/graphql-server/node_modules",
			ProjectPath:    "/Users/dev/projects/graphql-server",
			Basename:       "node_modules",
			SizeBytes:      175 * 1024 * 1024,
			LastModified:   now.Add(-45 * 24 * time.Hour),
			Status:         model.StatusReady,
			PackageManager: model.PackageManagerNPM,
			PackageName:    "graphql-server",
			PackageVersion: "3.0.0",
		},
	}
}
